### ISSUE TITLE
Segmentation fault on use with known good rules

### ISSUE THREAD

**Issue by scherma** [nospaceships/node-yara#9]
I would like to use this library but the basic examples do not work with [the ruleset that I would like to use](https://github.com/Neo23x0/signature-base). On attempting to configure the scanner with the above rules I get a segmentation fault; if I try to iterate over each individual rule file and configure and then call the scanner with that file, I get the error 

`Error: Please call configure() before scan()
    at Scanner.scan (/usr/local/unsafehex/build/nodetest/node_modules/yara/index.js:71:19)
    at /usr/local/unsafehex/build/nodetest/index.js:52:16
    at /usr/local/unsafehex/build/nodetest/node_modules/yara/index.js:58:4`

I haven't had time to dig in to your code yet (not sure if my skills are up to it either) but I'm wondering if this is down to node's preference for async; it feels like node is trying to supply stuff to the yara API in an order that is not expected and causing it to complain.

**Comment by stephenwvickers** [comment]
Hi @scherma 

Apologies for the delay.

The error you receive above is likely because you are not waiting for the scanner to finish before running a scan.  Rule compilation is async, and you should provide a callback to each invocation to configure().  Also note that each call to configure() will actually overwrite the rules compiled in the previous run.

Can you please confirm which version of this module you are using, and provide an example program that illustrates the issue then I can troubleshoot.

Thanks

Steve
